// I think we need to import global styles to make sure they're available to the packaged module
// import '@/styles/main.scss'

export { default as Avatar } from './Avatar/Avatar.vue'
export { default as Button } from './Button/Button.vue'
export { default as Card } from './Card/Card.vue'
export { default as CardActions } from './Card/Actions/Actions.vue'
export { default as CardAside } from './Card/Aside/Aside.vue'
export { default as CardHeader } from './Card/Header/Header.vue'
export { default as Slider } from './Slider/Slider.vue'
export { default as ToggleSwitch } from './Toggle/ToggleSwitch.vue'
export { default as RadioButton } from './Radio/RadioButton.vue'
export { default as Tag } from './Tag/Tag.vue'
export { default as Checkbox } from './Checkbox/Checkbox.vue'
export { default as TagGroup } from './TagGroup/TagGroup.vue'
